### PR TITLE
upgrade to apptainer and ubuntu22.04(jammy)

### PR DESCRIPTION
**Pull request by d-a-v**
It also brings a fully rootless installer thanks to apptainer v1.1

- timescaledb tuner is moved to build stage
- new command `postgres admin` for the initial admin access

### CODE REVIEW

**Comment by glentner** [comment]
Hey, thanks for contributing, love it. 🥃

**Comment by glentner** [comment]
Couple of things to consider:

I wrote this for use on high-performance computing cluster (specifically at Purdue University) but is also usable at other sites and likely DoE labs. 

* We don't as of now have Apptainer (but I'm interested in this I suppose). We only have Singularity.
* The reason I have the tune step as a second stage thing and not as part of the build is because it can change depending on what node you land on. You could have 128-cores and a TB of memory, or 20 cores and very little. So within your batch job script, you would write `tune` after `initdb` to let it make good choices.

**Comment by glentner** [comment]
If you wouldn't mind, let's split this up into separate PRs.

First PR to update to PG 14. Second PR to clean up, add `admin` workflow, etc.

Then I would be interested in letting _Singularity_ and _Apptainer_ co-exist simultaneously here. We could facilitate that by leaving both build files, and use a variable in the script and maybe a bit of logic.

**Comment by d-a-v** [comment]
Got it. 
I don't mind if you prefer to do some or all steps (not seeking for credits).
I'll try to find time next week for this, in your order.

> Then I would be interested in letting Singularity *and* Apptainer co-exist simultaneously here

There's no need for that. Apptainer has internal transition helpers which allow to use `singularity` command as before, also `SINGULARITY*` env variables. So your version would currently works with Apptainer (but `ubuntu:latest` would have to switch to `focal / 20.04` for the timescaledb part to work).
I am also running an HPC cluster (a small one with Slurm), including using GPUS.
I found Apptainer very efficient for using remote GPU and/or EGL.
What's great with Apptainer is that `sudo` becomes completely unnecessary.

**Comment by d-a-v** [comment]
closing per #2

**Pull request closed without merging**
